# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drmugg123/Downloads/muggengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drmugg123/Downloads/muggengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drmugg123/Downloads/muggengine/CMakeFiles /home/drmugg123/Downloads/muggengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drmugg123/Downloads/muggengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named muggengine

# Build rule for target.
muggengine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 muggengine
.PHONY : muggengine

# fast build rule for target.
muggengine/fast:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/build
.PHONY : muggengine/fast

src/compressionhandler.o: src/compressionhandler.cpp.o
.PHONY : src/compressionhandler.o

# target to build an object file
src/compressionhandler.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/compressionhandler.cpp.o
.PHONY : src/compressionhandler.cpp.o

src/compressionhandler.i: src/compressionhandler.cpp.i
.PHONY : src/compressionhandler.i

# target to preprocess a source file
src/compressionhandler.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/compressionhandler.cpp.i
.PHONY : src/compressionhandler.cpp.i

src/compressionhandler.s: src/compressionhandler.cpp.s
.PHONY : src/compressionhandler.s

# target to generate assembly for a file
src/compressionhandler.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/compressionhandler.cpp.s
.PHONY : src/compressionhandler.cpp.s

src/file.o: src/file.cpp.o
.PHONY : src/file.o

# target to build an object file
src/file.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/file.cpp.o
.PHONY : src/file.cpp.o

src/file.i: src/file.cpp.i
.PHONY : src/file.i

# target to preprocess a source file
src/file.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/file.cpp.i
.PHONY : src/file.cpp.i

src/file.s: src/file.cpp.s
.PHONY : src/file.s

# target to generate assembly for a file
src/file.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/file.cpp.s
.PHONY : src/file.cpp.s

src/filehandler.o: src/filehandler.cpp.o
.PHONY : src/filehandler.o

# target to build an object file
src/filehandler.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/filehandler.cpp.o
.PHONY : src/filehandler.cpp.o

src/filehandler.i: src/filehandler.cpp.i
.PHONY : src/filehandler.i

# target to preprocess a source file
src/filehandler.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/filehandler.cpp.i
.PHONY : src/filehandler.cpp.i

src/filehandler.s: src/filehandler.cpp.s
.PHONY : src/filehandler.s

# target to generate assembly for a file
src/filehandler.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/filehandler.cpp.s
.PHONY : src/filehandler.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/minilzo.o: src/minilzo.c.o
.PHONY : src/minilzo.o

# target to build an object file
src/minilzo.c.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/minilzo.c.o
.PHONY : src/minilzo.c.o

src/minilzo.i: src/minilzo.c.i
.PHONY : src/minilzo.i

# target to preprocess a source file
src/minilzo.c.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/minilzo.c.i
.PHONY : src/minilzo.c.i

src/minilzo.s: src/minilzo.c.s
.PHONY : src/minilzo.s

# target to generate assembly for a file
src/minilzo.c.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/minilzo.c.s
.PHONY : src/minilzo.c.s

src/shaderprogram.o: src/shaderprogram.cpp.o
.PHONY : src/shaderprogram.o

# target to build an object file
src/shaderprogram.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/shaderprogram.cpp.o
.PHONY : src/shaderprogram.cpp.o

src/shaderprogram.i: src/shaderprogram.cpp.i
.PHONY : src/shaderprogram.i

# target to preprocess a source file
src/shaderprogram.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/shaderprogram.cpp.i
.PHONY : src/shaderprogram.cpp.i

src/shaderprogram.s: src/shaderprogram.cpp.s
.PHONY : src/shaderprogram.s

# target to generate assembly for a file
src/shaderprogram.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/shaderprogram.cpp.s
.PHONY : src/shaderprogram.cpp.s

src/tcpclient.o: src/tcpclient.cpp.o
.PHONY : src/tcpclient.o

# target to build an object file
src/tcpclient.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/tcpclient.cpp.o
.PHONY : src/tcpclient.cpp.o

src/tcpclient.i: src/tcpclient.cpp.i
.PHONY : src/tcpclient.i

# target to preprocess a source file
src/tcpclient.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/tcpclient.cpp.i
.PHONY : src/tcpclient.cpp.i

src/tcpclient.s: src/tcpclient.cpp.s
.PHONY : src/tcpclient.s

# target to generate assembly for a file
src/tcpclient.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/tcpclient.cpp.s
.PHONY : src/tcpclient.cpp.s

src/texture.o: src/texture.cpp.o
.PHONY : src/texture.o

# target to build an object file
src/texture.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/texture.cpp.o
.PHONY : src/texture.cpp.o

src/texture.i: src/texture.cpp.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/texture.cpp.i
.PHONY : src/texture.cpp.i

src/texture.s: src/texture.cpp.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/texture.cpp.s
.PHONY : src/texture.cpp.s

src/udpclient.o: src/udpclient.cpp.o
.PHONY : src/udpclient.o

# target to build an object file
src/udpclient.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/udpclient.cpp.o
.PHONY : src/udpclient.cpp.o

src/udpclient.i: src/udpclient.cpp.i
.PHONY : src/udpclient.i

# target to preprocess a source file
src/udpclient.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/udpclient.cpp.i
.PHONY : src/udpclient.cpp.i

src/udpclient.s: src/udpclient.cpp.s
.PHONY : src/udpclient.s

# target to generate assembly for a file
src/udpclient.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/udpclient.cpp.s
.PHONY : src/udpclient.cpp.s

src/window.o: src/window.cpp.o
.PHONY : src/window.o

# target to build an object file
src/window.cpp.o:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/window.cpp.o
.PHONY : src/window.cpp.o

src/window.i: src/window.cpp.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.cpp.i:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/window.cpp.i
.PHONY : src/window.cpp.i

src/window.s: src/window.cpp.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.cpp.s:
	$(MAKE) -f CMakeFiles/muggengine.dir/build.make CMakeFiles/muggengine.dir/src/window.cpp.s
.PHONY : src/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... muggengine"
	@echo "... rebuild_cache"
	@echo "... src/compressionhandler.o"
	@echo "... src/compressionhandler.i"
	@echo "... src/compressionhandler.s"
	@echo "... src/file.o"
	@echo "... src/file.i"
	@echo "... src/file.s"
	@echo "... src/filehandler.o"
	@echo "... src/filehandler.i"
	@echo "... src/filehandler.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/minilzo.o"
	@echo "... src/minilzo.i"
	@echo "... src/minilzo.s"
	@echo "... src/shaderprogram.o"
	@echo "... src/shaderprogram.i"
	@echo "... src/shaderprogram.s"
	@echo "... src/tcpclient.o"
	@echo "... src/tcpclient.i"
	@echo "... src/tcpclient.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/udpclient.o"
	@echo "... src/udpclient.i"
	@echo "... src/udpclient.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

